---
title: "README"
output: html_document
date: "2026-04-01"
---
Our  package centers a dataset from kaggle called Global Economy Indicators. It measures economic indicators such as population, the year, the country name, the Gross Domestic Product (GDP), and the AMA exchange rate spanning from 1970 until 2021. Our functions would mainly deal with providing information about a country and its factors such as GDP per population of a specific year, the highest GDP per year, and the country's GDP per population over time.

The goal of the package is to allow users to learn about economic indicators of a country in a specific time such as finding the AMA exchange rate and the indicator for agriculture, hunting, forestry, fishing in a specific year and finding out what was the country's GDP per population over time. The package was built to be able to be used on specific values, or be able to loop the function over the entire dataset. Some of the functions are more beginner friendly such as highest_gdp_per_year() and mean_gdp_per_year(), while others require a bit more of an economic background to be able to understand what the output is telling you. 

As stated above, our package was created specifically with one dataset in mind so the functions cannot work on outside datasets. However this package should give some beginner insight on what kind of data you may want from a different dataset. This package can be used to learn about economic indicators and what they mean for a country. The inner workings of the functions can give you a background on how to manipulate other datasets to find the same type of information we are giving you. Whether you have a vast knowledge of economics and how it impacts a country, or you are just starting out, this package can break down the data and present it in an easily digestible way. 
